# A hospital administrator is studying the number of patients 
# arriving at the emergency department each hour during a 
# night shift.
# She wants to verify if the average number of patients per
# hour is different from two, that is value historically assumed.  

# We assume that the data are generated by iid Poisson rvs.

theta0 <- 2

y <- c(4, 2, 3, 3, 2, 0, 4, 5, 4, 4) # Milan
y <- c(2, 3, 1, 4, 0, 2, 3, 1, 2, 5) # Trieste

# 2a) LRT
lik_pois <- function(lam, n, sumy) log(lam) * sumy - n*lam


# 2b) Wald


# 2c) Score




## one sided:

# 3a) LRT
lik_pois <- function(lam, n, sumy) log(lam) * sumy - n*lam


# 3b) Wald


# 3c) Score
